server:
  port: 2030


spring:
  application:
    name: com-dualwings-sales
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dysalesystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
        

  mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.dualwings.sales.pro  #可用可不用
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# REDIS (RedisProperties)

 
#spring.redis.jedis.pool.max-active=8
#spring.redis.jedis.pool.max-wait=-1
#spring.redis.jedis.pool.max-idle=8
#spring.redis.jedis.pool.min-idle=0
#spring.redis.timeout=5000


  #注册中心的选择


