server:
  port: 2020


spring:
  application:
    name: com-dualwings-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.68.92:3306/dysystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: dualwings0522
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
        
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dualwings.order.domain.entity


